// meetings/1_frameworks/react/testing/src/components/message-board.js
import React, { Component } from 'react';
import openSocket from 'socket.io-client';

class MessageBoard extends Component {
  constructor(props) {
    super(props);
    this.state = {
      messages: [],
      text: "",
    }
    this.setUpSockets.bind(this);
    this.receiveMessage.bind(this);
    this.setUpSockets();
  }


  setUpSockets() {
    this.socket = openSocket('http://api.tgt101.com:4444');
    const { board } = this.props;
    this.socket.emit('getAllMessages', board);
    this.socket.on('allMessages', (data) => {
      console.log(data);
      const boardMess = data
        .filter(m => m.board === board)
        .map(m => m.text);
      this.setState({
        messages: boardMess,
      })
    });
    this.socket.on('message', (data) => {
      this.receiveMessage(data);
    })
  }

  receiveMessage(data) {
    const { board } = this.props;
    const { messages } = this.state;
    if (data.board === board) {
      console.log("Made")
      messages.push(data.text);
      console.log(messages);
      this.setState({
        messages,
      })
    }
  }

  sendMessage() {
    const { text } = this.state;
    const { board } = this.props;
    this.socket.emit("newMessage", {
      text,
      board,
    });
    this.setState({ text: "" })
  }

  typeMessage(event) {
    this.setState({ text: event.target.value });
  }

  render() {
    const { messages, text } = this.state;
    return (
      <h1>
        <p> Hello </p>
        { messages.map(message => (
          <p>
            { message }
          </p>
        )) }
        <input
          type="text"
          value={text}
          onChange={(event) => this.typeMessage(event)}
        />
        <button
          onClick={() => this.sendMessage()}
        >
          Send Message
        </button>
      </h1>
    )
  }
}

export default MessageBoard;

// meetings/1_frameworks/angular/prep-app/src/app/message-board/message-board.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Socket } from 'ngx-socket-io';
import { filter, take } from 'rxjs/operators';
interface IMessage {
  board: string;
  text: string;
}

@Component({
  selector: 'app-message-board',
  templateUrl: './message-board.component.html',
  styleUrls: ['./message-board.component.scss']
})
export class MessageBoardComponent implements OnInit {
  @Input() board !: string;

  public $messages = this.socket.fromEvent<IMessage[]>('allMessages');
  public $newMessage = this.socket.fromEvent<IMessage>('message');

  public text !: string;
  private messages: string[] = [];

  constructor(
    private socket: Socket,
  ) { }

  ngOnInit() {
    this.$messages.subscribe(messages => {
      console.log(this.board, messages);
      this.messages = messages.filter(message => message.board === this.board).slice(0).map(message => message.text);
    });

    this.$newMessage.pipe(
      filter(message => message.board === this.board)
    ).subscribe(message => {
      this.messages.push(message.text);
    });

    this.getAllMessage();
  }

  sendMessage() {
    this.socket.emit('newMessage', {
      board: this.board,
      text: this.text,
    });
    this.text = '';
  }

  getAllMessage() {
    this.socket.emit('getAllMessages', this.board);
  }

}

<div id="root">
  <div id="messages">
    <div *ngFor="let message of messages" class="message">
      {{ message }}
    </div>
  </div>
  <input
    type="text"
    [(ngModel)]="text"
  />
  <button
    (click)="sendMessage()"
  >
    Send Message
  </button>
</div>
